name: my_woo_english
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  responsive_sizer: ^3.1.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  device_preview: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
          weight: 300
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair_display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 600
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
    - family: Alegreya
      fonts:
        - asset: assets/fonts/alegreya/Alegreya-Medium.ttf
          weight: 300
        - asset: assets/fonts/alegreya/Alegreya-Regular.ttf
          weight: 400
        - asset: assets/fonts/alegreya/Alegreya-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/alegreya/Alegreya-Bold.ttf
          weight: 700


